###############################################################################
# Auto-generated by `jupyter-book config`
# If you wish to continue using _config.yml, make edits to that file and
# re-generate this one.
###############################################################################
author = 'MulQuaBio collective!'
bibtex_bibfiles = ['references.bib']
bibtex_default_style = 'mqb_nourl'
bibtex_reference_style = 'author_year'
comments_config = {'hypothesis': False, 'utterances': False}
copyright = '2024'
exclude_patterns = ['**.ipynb_checkpoints', '**/.virtual_documents/**', '.DS_Store', 'Thumbs.db', '_build', 'code/*', 'content.md', 'data/*', 'hpc/instructions/**', 'intro-adv-data.md', 'lectures/*', 'notebooks/experimental/**', 'notebooks/interactions_alt.ipynb', 'readings/*', 'refs/*', 'results/*', 'sandbox/*', 'sols/*', 'tools/*']
extensions = ['sphinx_togglebutton', 'sphinx_copybutton', 'myst_nb', 'jupyter_book', 'sphinx_thebe', 'sphinx_comments', 'sphinx_external_toc', 'sphinx.ext.intersphinx', 'sphinx_design', 'sphinx_book_theme', 'mqb_bibstyle', 'sphinxcontrib.bibtex', 'sphinx_jupyterbook_latex', 'sphinx_multitoc_numbering']
external_toc_exclude_missing = False
external_toc_path = '_toc.yml'
html_baseurl = ''
html_css_files = ['custom.css']
html_favicon = ''
html_js_files = ['https://cdn.jsdelivr.net/npm/@iframe-resizer/child@latest']
html_logo = '_static/images/logo.png'
html_sourcelink_suffix = ''
html_static_path = ['_static']
html_theme = 'sphinx_book_theme'
html_theme_options = {'search_bar_text': 'Search this book...', 'launch_buttons': {'notebook_interface': 'jupyterlab', 'binderhub_url': 'https://mybinder.org', 'jupyterhub_url': '', 'thebe': False, 'colab_url': 'https://colab.research.google.com', 'deepnote_url': ''}, 'path_to_docs': '', 'repository_url': 'https://github.com/MulQuaBio/MQB', 'repository_branch': 'master', 'extra_footer': '', 'home_page_in_toc': True, 'announcement': '', 'analytics': {'google_analytics_id': '', 'plausible_analytics_domain': '', 'plausible_analytics_url': 'https://plausible.io/js/script.js'}, 'use_repository_button': True, 'use_edit_page_button': False, 'use_issues_button': True}
html_title = 'MulQuaBio'
latex_engine = 'pdflatex'
mathjax_path = 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js'
myst_enable_extensions = ['amsmath', 'dollarmath', 'html_image', 'linkify', 'colon_fence']
myst_heading_anchors = 3
myst_substitutions = {'static': '_static', 'graphics': 'notebooks/graphics'}
myst_url_schemes = ['mailto', 'http', 'https']
nb_execution_allow_errors = True
nb_execution_cache_path = ''
nb_execution_excludepatterns = []
nb_execution_in_temp = False
nb_execution_mode = 'off'
nb_execution_timeout = 30
nb_output_stderr = 'show'
nb_render_markdown_format = 'myst'
numfig = True
pygments_style = 'sphinx'
suppress_warnings = ['myst.domains']
use_jupyterbook_latex = True
use_multitoc_numbering = True
